export const homeObjOne = {
    lightBg: false,
    primary: true,
    imgStart: "",
    lightTopLine: true,
    lightText: true,
    lightTextDesc: true,
    buttonLabel: "Get Started",
    description: "We help Businesss owners increase their revenue. Our team of unique specialist can help you acheive your business goals.",
    headline: "Lead Generation Specialist for Online Businesses",
    topLine: "Marketing Agency",
    img: require('../../images/svg1.svg').default,
    alt: "Image",
    start: "",
};

export const homeObjTwo = {
    lightBg: true,
    primary: false,
    imgStart: "start",
    lightTopLine: false,
    lightText: false,
    lightTextDesc: false,
    buttonLabel: "Get Started",
    description: "We help Businesss owners increase their revenue. Our team of unique specialist can help you acheive your business goals.",
    headline: "Lead Generation Specialist for Online Businesses",
    topLine: "Marketing Agency",
    img: require('../../images/svg5.svg').default,
    alt: "Image",
    start: "true",
};

export const homeObjThree = {
    lightBg: false,
    primary: true,
    imgStart: "",
    lightTopLine: true,
    lightText: true,
    lightTextDesc: true,
    buttonLabel: "Get Started",
    description: "We help Businesss owners increase their revenue. Our team of unique specialist can help you acheive your business goals.",
    headline: "Lead Generation Specialist for Online Businesses",
    topLine: "Marketing Agency",
    img: require('../../images/svg3.svg').default,
    alt: "Image",
    start: "",
};

export const homeObjFour = {
    lightBg: true,
    primary: false,
    imgStart: "start",
    lightTopLine: false,
    lightText: false,
    lightTextDesc: false,
    buttonLabel: "Get Started",
    description: "We help Businesss owners increase their revenue. Our team of unique specialist can help you acheive your business goals.",
    headline: "Lead Generation Specialist for Online Businesses",
    topLine: "Marketing Agency",
    img: require('../../images/svg4.svg').default,
    alt: "Image",
    start: "true",
};